version: '3.8'

services:
  cert_auth_server:
    build:
      context: ./cert_auth_server
    ports:
      - "4000:4000"
    networks:
      - mynetwork

  web_server:
    build:
      context: ./web_server
    ports:
      - "3000:3000"
    depends_on:
      - cert_auth_server
    networks:
      - mynetwork

  client_server:
    build:
      context: ./client_server
    depends_on:
      - cert_auth_server
      - web_server
      - sidecar_server
    networks:
      - mynetwork

  sidecar_server:
    build:
      context: ./sidecar_server
    ports:
      - "5000:5000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
